ENV['RCT_NEW_ARCH_ENABLED'] = '0'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, min_ios_version_supported
prepare_react_native_project!
target 'Clarora-iOS' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :new_arch_enabled => false,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath], :mac_catalyst_enabled => false)

    # react-native 0.77 的 React-jsinspector podspec 头文件集合缺少
    # jsinspector-modern 的新增头文件（如 TracingAgent.h），与 macOS 同修。
    react_common = %q($(PODS_ROOT)/../../node_modules/react-native/ReactCommon)
    jsinspector_dir = %q($(PODS_ROOT)/../../node_modules/react-native/ReactCommon/jsinspector-modern)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['HEADER_SEARCH_PATHS'] = [config.build_settings['HEADER_SEARCH_PATHS'], react_common, jsinspector_dir].compact.join(' ')
    end
  end
end
